/* eslint-disable prettier/prettier */
export default {
  ok: 'OK',
  cancel: 'Cancel',
  selectLng: 'Choose the Language',
  fieldRequired: 'Field Required',
  'Esqueci minha senha': 'I forget my password',
  'Recurar Senha': 'Recover Password',
  Enviar: 'Submit',
  'Cadastrar-se': 'Sign-Up',
  Endreço: 'address',
  uf: 'state',
  cidade: 'city',
  'CEP não encontrado.': 'zip code not found',
  'Formato de CEP inválido.': 'zip code invalid format.',
  Nome: 'Name',
  CPF: 'Fiscal Number',
  Celular: 'Mobile Phone',
  Sexo: 'Gender',
  Feminino: 'Female',
  Masculino: 'Masculino',
  Escolha: 'Choose',
  'Campo obrigatório': 'Field Required',
  'Data inválida': 'Invalid Date',
  'CPF inválido': 'Invalid Fiscal Number',
  'E-mail inválido': 'Invalid E-mail',
  'Data de Nascimento': 'Date of birth',
  Profissão: 'Profession',
  Cep: 'Zip Code',
  Bairro: 'Neighborhood',
  Cidade: 'City',
  UF: 'State',
  'Nome da Mãe': `Mother's name`,
  Senha: 'Password',
  'Aceitar termos': 'Accept terms',
  'Ler Termos de uso': 'Read Terms of Use',
  Laboratórios: 'Laboratories',
  'Iniciar Exame': 'Start Exam',
  'Selecione a cidade:': 'Select city:',
  'Limpar filtro': 'Clear filter',
  Serviços: 'Services',
  'Dados enviados com sucesso': 'Data sent successfully',
  'Preencher o campo OUTROS em sintomas':
    'Fill in the OTHERS field in symptoms ',
  'Preencher o campo OUTROS em sinais clínicos':
    'Fill in the OTHERS field in clinical signs ',
  'Escolha o estado para continuar': 'Choose the state to continue',
  'Escolha a cidade para continuar': 'Choose the city to continue',
  'Preencher o campo país para continuar':
    'Fill in the country field to continue ',
  'Escolha ao menos uma opção sobre a suspeita de covid do paciente': `Choose at least one option about the patient's suspected covid`,
  'Escolha ao menos uma opção sobre o local de suspeita de covid do paciente': `Choose at least one option about the patient's suspected covid location`,
  'Preencher o campo Especificação de OUTROS para continuar':
    'Fill in the OTHERS Specification field to continue',
  'Preencher o campo Caso Fonte': 'Fill in the Case Source field',
  'Preencher o campo Nome, Endereço e Contato para continuar':
    'Fill in the Name, Address and Contact field to continue',
  FINALIZAR: 'FINISH',
  PRÓXIMO: 'NEXT',
  'Informações Clínicas': 'Clinical Information',
  VOLTAR: 'BACK',
  'Selecione os sinais e sintomas apresentados':
    'Select the signs and symptoms presented',
  FEBRE: 'FEVER',
  TOSSE: 'COUGH',
  'CORIZA/CONGESTÃO NASAL': 'CORIZA/NASAL CONGESTION',
  'DOR NO CORPO': 'BODY ACHE',
  ESCARRO: 'SPUTUM',
  'DOR DE CABEÇA': 'HEADACHE',
  FRAQUEZA: 'WEAKNESS',
  'CANSAÇO / FALTA DE AR': 'TIRING / LACK OF AIR',
  DIARREIA: 'DIARRHEA',
  'FALDA DE APETITE': 'LACK OF APPETITE',
  'NÁUSEA/VÔMITOS': 'NAUSEA/VOMITING',
  'PACIENTE TEM HISTÓRICO DE VIAGEM ATÉ 14 DIAS ANTES DO INÍCIO DOS SINTOMAS?':
    'DOES THE PATIENT HAVE A TRAVEL HISTORY UP TO 14 DAYS BEFORE THE SYMPTOMS BEGIN?',
  Brasil: 'Brazil',
  Estado: 'State',
  Exterior: 'Outdoor',
  'O PACIENTE TEVE CONTATO PRÓXIMO COM UMA PESSOA QUE SEJA CASO SUSPEITO DE NOVO CORONAVÍRUS (COVID-19)?':
    'DOES THE PATIENT HAVE NEXT CONTACT WITH A PERSON WHO IS A SUSPECTED CASE OF NEW CORONAVIRUS (COVID-19)?',
  NÃO: 'NO',
  'NÃO SABE': 'DO NOT KNOW',
  SIM: 'YES',
  'UNIDADE DE SAÚDE': 'HEALTH UNIT',
  DOMICÍLIO: 'RESIDENCE',
  'LOCAL DE TRABALHO': 'WORKPLACE',
  DESCONHECIDO: 'UNKNOWN',
  OUTRO: 'OTHER',
  Especificar: 'To specify',
  'O PACIENTE TEVE CONTATO PRÓXIMO COM UMA PESSOA QUE SEJA CASO CONFIRMADO DE NOVO CORONAVÍRUS (COVID-19)?':
    'DOES THE PATIENT HAVE NEXT CONTACT WITH A PERSON WHO IS CONFIRMED AS NEW CORONAVIRUS (COVID-19)?',
  'NOME DO CASO FONTE': 'SOURCE CASE NAME',
  'ESTEVE EM UNIDADE DE SAÚDE NOS ÚLTIMOS 14 DIAS?(PRONTO SOCORRO;INTERNAÇÃO; UTI)':
    'HAVE YOU BEEN IN A HEALTH UNIT IN THE LAST 14 DAYS? (FIRST AID; HOSPITALIZATION; ICU)',
  'INFORMAR NOME DA UNIDADE': 'INFORM UNIT NAME',
  'Selecione as doenças associadas': 'Select associated diseases',
  'HIPERTENSÃO ARTERIAL': 'ARTERIAL HYPERTENSION',
  DIABETES: 'DIABETES',
  'ALTERAÇÃO COLESTEROL/TRIGLICÉRIDES': 'CHOLESTEROL / TRIGLYCERIDES CHANGE',
  OBESIDADE: 'OBESITY',
  'DOENÇAS REUMATOLÓGICAS': 'RHEUMATOLOGICAL DISEASES',
  Qual: 'What',
  'DPOC (ENFISEMA)': 'COPD (EMPHYSEMA)',
  ASMA: 'ASTHMA',
  RINITE: 'RHINITIS',
  'APNEIA DO SONO': 'SLEEP APNEA',
  'NEOPLASIA / CÂNCER': 'NEOPLASIA / CANCER',
  'INSUFICIÊNCIA RENAL': 'RENAL INSUFFICIENCY',
  'DOENÇAS HEPÁTICAS': 'LIVER DISEASES',
  OUTROS: 'OTHERS',
  'Meus Laudos': 'My Exams',
  Atendimento: 'Attendance',
  Triagem: 'Screening',
  Diagnóstico: 'Diagnosis',
  Finalizado: 'Finished',
  Positivo: 'Positive',
  Negativo: 'Negative',
  'Mais opções': 'More Options',
  'Meus Dados': 'Profile',
  Suporte: 'Suport',
  'Fazer logout': 'Logout',
  Telefone: 'Phone',
  'Entre em contato com nosso suporte por e-mail ou telefone': 'Contact our support by email or phone.',
  'D I A G N Ó S T I C O S': 'D I A G N O S T I C S',
  'Cadastro conclúido! por favor, dirija-se ao laboratório escolhido para a realizar coleta': 'Registration completed! please go to the chosen laboratory to collect it',
  'Português': 'Portuguese',
  'Inglês': 'English',
  'Espanhol': 'Spanish',
  Mais: 'More',
  'Laboratório de Pesquisa por Cidade': 'Research Laboratory by City',
  'Selecione as ': 'Select the ',
  'Selecione os ': 'Select the ',
  'sinais ': 'signs ',
  'e ': 'and ',
  'sintomas ': 'symptoms ',
  'apresentados': 'presented',
  'doenças associadas': 'associated diseases',
  'Sobrenome': 'Last name',
  'Buscar por Cidade': 'Search by City',
  'Pedido': 'Order',
  'Tipo de exame': 'Exam type',
  'Tipo de amostra': 'Sample type',
  'Resultado': 'Result',
  'O paciente tem histórico de ': 'The patient has a history of ',
  'viagem recente? ': 'recent trip? ',
  '(período de 14 dias)': '(14 day period)',
  'O paciente teve ': 'The patient had ',
  'contato ': 'contact ',
  'com algum caso suspeito ou confirmado de COVID-19?': 'with a suspected or confirmed case of COVID-19?',
  'O paciente esteve em alguma ': 'The patient was in some ',
  'Unidade de Saúde ': 'Health Unit ',
  'nos últimos 14 dias? (Pronto Socorro, Internação, UTI)': 'in the last 14 days? (Emergency Room, Hospitalization, ICU)',
  'FALTA DE APETITE': 'LACK OF APPETITE',
  'Coriza': 'Coryza',
  'Qual País': 'Which Country',
  'Ver Todos': 'See All',
  'apresentado ': 'presented',
  'Salvar dados para login': 'Save login data',
  'Menu Biogenetics': 'Biogenetics Menu',
  'Aqui você poderá editar os seus dados, pessoais idioma e mais': 'Here you can edit your personal data, language and more',
  'DADOS DO USUÁRIO': 'USER DATA',
  'TERMOS DE USO': 'TERMS OF USE',
  'IDIOMAS': 'LANGUAGES',
  'CONTATO': 'CONTACT',
  'SAIR': 'SIGN OUT',
  'Perfil': 'Profile',
  'Download realizado com sucesso': 'Download successful',
  'Consulte o status e o resultado dos seus exames realizados': 'Check the status and results of your exams performed',
  'Exame': 'Exam',
  'Exames': 'Exams',
  'EXAME': 'EXAM',
  'Laudo': 'Report',
  'Paciente': 'Patient',
  'DATA': 'DATE',
  'VER LAUDO': 'VIEW REPORT',
  'Baixar PDF': 'Download PDF',
  'Como podemos te ajudar hoje? Escolha uma das opções abaixo': 'How can we help you today? Choose one of the options below',
  'Aqui você consegue encontrar os laboratórios mais próximos de você': 'Here you can find the laboratories closest to you',
  'Buscar por CEP': 'Search by zip code',
  'INICIAR': 'START',
  'TELEFONE': 'PHONE',
  'Início': 'Start',
  'Olá!': 'Helo!',
  'Aqui estão os laboratórios mais próximos de você': 'Here are the laboratories closest to you',
  LIGAR: 'TO CALL'
};