export default {
  ok: 'OK',
  cancel: 'Cancel',
  selectLng: 'Choose the Language',
  fieldRequired: 'Field Required',
  'Esqueci minha senha': 'I forget my password',
  'Recurar Senha': 'Recover Password',
  Enviar: 'Submit',
  'Cadastrar-se': 'Sign-Up',
  Endreço: 'address',
  uf: 'state',
  cidade: 'city',
  'CEP não encontrado.': 'zip code not found',
  'Formato de CEP inválido.': 'zip code invalid format.',
  Nome: 'Name',
  CPF: 'Fiscal Number',
  Celular: 'Mobile Phone',
  Sexo: 'Gender',
  Feminino: 'Female',
  Masculino: 'Masculino',
  Escolha: 'Choose',
  'Campo obrigatório': 'Field Required',
  'Data inválida': 'Invalid Date',
  'CPF inválido': 'Invalid Fiscal Number',
  'E-mail inválido': 'Invalid E-mail',
  'Data de Nascimento': 'Date of birth',
  Profissão: 'Profession',
  Cep: 'Zip Code',
  Bairro: 'Neighborhood',
  Cidade: 'City',
  UF: 'State',
  'Nome da Mãe': `Mother's name`,
  Senha: 'Password',
  'Aceitar termos': 'Accept terms',
  'Ler Termos de uso': 'Read Terms of Use',
  Laboratórios: 'Laboratories',
  'Iniciar Exame': 'Start Exam',
  'Selecione a cidade:': 'Select city:',
  'Limpar filtro': 'Clear filter',
  Serviços: 'Services',
  'Dados enviados com sucesso': 'Data sent successfully',
  'Preencher o campo OUTROS em sintomas':
    'Fill in the OTHERS field in symptoms ',
  'Preencher o campo OUTROS em sinais clínicos':
    'Fill in the OTHERS field in clinical signs ',
  'Escolha o estado para continuar': 'Choose the state to continue',
  'Escolha a cidade para continuar': 'Choose the city to continue',
  'Preencher o campo país para continuar':
    'Fill in the country field to continue ',
  'Escolha ao menos uma opção sobre a suspeita de covid do paciente': `Choose at least one option about the patient's suspected covid`,
  'Escolha ao menos uma opção sobre o local de suspeita de covid do paciente': `Choose at least one option about the patient's suspected covid location`,
  'Preencher o campo Especificação de OUTROS para continuar':
    'Fill in the OTHERS Specification field to continue',
  'Preencher o campo Caso Fonte': 'Fill in the Case Source field',
  'Preencher o campo Nome, Endereço e Contato para continuar':
    'Fill in the Name, Address and Contact field to continue',
  FINALIZAR: 'FINISH',
  PRÓXIMO: 'NEXT',
  'Informações Clínicas': 'Clinical Information',
  VOLTAR: 'BACK',
  'Selecione os sinais e sintomas apresentados':
    'Select the signs and symptoms presented',
};
