/* eslint-disable prettier/prettier */
export default {
  ok: 'OK',
  cancel: 'Cancelar',
  selectLng: 'Elige el idioma',
  'fieldRequired': 'Campo requerido',
  'Esqueci minha senha': 'Olvido mi contraseña',
  'Recuperar Senha': 'Recuperar contraseña',
  Enviar: 'Entregar',
  'Cadastrar-se': 'Regístrate',
  Endereço: 'Dirección',
  uf: 'estado',
  cidade: 'Ciudad',
  'CEP não encontrado.': 'Código postal no encontrado.',
  'Formato de CEP inválido.': 'Formato de código postal no válido.',
  Nome: 'Nombre',
  CPF: 'CPF',
  Celular: 'Cell',
  Sexo: 'Género',
  Feminino: 'Mujer',
  Masculino: 'Masculino',
  Escolha: 'Elección',
  'Campo obrigatório': 'Campo obligatorio',
  'Data inválida': 'Fecha invalida',
  'CPF inválido': 'Número de seguro social inválido',
  'E-mail inválido': 'E-mail inválido',
  'Data de Nascimento': 'Fecha de nacimiento',
  Profissão: 'Profesión',
  Cep: 'Código postal',
  Bairro: 'Vecindario',
  Cidade: 'Ciudad',
  UF: 'Estado',
  'Nome da Mãe': `Nombre de la madre`,
  Senha: 'Contraseña',
  'Aceitar termos': 'Aceptar los terminos',
  'Ler Termos de uso': 'Leer condiciones de uso',
  Laboratórios: 'Laboratorios',
  'Iniciar Exame': 'Iniciar examen',
  'Selecione a cidade': 'Selecione a cidade',
  'Limpar filtro': 'Filtro claro',
  Serviços: 'Servicios',
  'Dados enviados com sucesso': 'Datos enviados con éxito',
  'Preencher o campo OUTROS em sintomas':
    'Complete el campo OTROS en síntomas',
  'Preencher o campo OUTROS em sinais clínicos':
    'Complete el campo OTROS en signos clínicos',
  'Escolha o estado para continuar': 'Elija el estado para continuar',
  'Escolha a cidade para continuar': 'Elige la ciudad para continuar',
  'Preencher o campo país para continuar':
    'Complete el campo del país para continuar',
  'Escolha ao menos uma opção sobre a suspeita de covid do paciente': `Elija al menos una opción sobre la sospecha de covid del paciente`,
  'Escolha ao menos uma opção sobre o local de suspeita de covid do paciente': `Elija al menos una opción sobre la sospecha de covid del paciente`,
  'Preencher o campo Especificação de OUTROS para continuar':
    'Complete el campo de especificación OTROS para continuar',
  'Preencher o campo Caso Fonte': 'Complete el campo Caso de origen',
  'Preencher o campo Nome, Endereço e Contato para continuar':
    'Complete el campo Nombre, Dirección y Contacto para continuar',
  FINALIZAR: 'TERMINAR',
  PRÓXIMO: 'SIGUIENTE',
  'Informações Clínicas': 'Información clínica',
  VOLTAR: 'VOLVER',
  'Selecione os sinais e sintomas apresentados':
    'Seleccione los signos y síntomas presentados',
  FEBRE: 'FIEBRE',
  TOSSE: 'TOS',
  'CORIZA/CONGESTÃO NASAL': 'CORIZA / CONGESTIÓN NASAL',
  'DOR NO CORPO': 'DOLOR EN EL CUERPO',
  ESCARRO: 'ESPUTO',
  'DOR DE CABEÇA': 'DOLOR DE CABEZA',
  FRAQUEZA: 'DEBILIDAD',
  'CANSAÇO / FALTA DE AR': 'CANSANCIO / FALTA DE AIRE',
  DIARREIA: 'DIARREA',
  'FALTA DE APETITE': 'FALTA DE APETITO',
  'NÁUSEA/VÔMITOS': 'NÁUSEAS VÓMITOS',
  'PACIENTE TEM HISTÓRICO DE VIAGEM ATÉ 14 DIAS ANTES DO INÍCIO DOS SINTOMAS?':
    '¿TIENE EL PACIENTE UN HISTORIAL DE VIAJES HASTA 14 DÍAS ANTES DE QUE COMIENZAN LOS SÍNTOMAS?',
  Brasil: 'Brasil',
  Estado: 'Expresar',
  Exterior: 'Exterior',
  'O PACIENTE TEVE CONTATO PRÓXIMO COM UMA PESSOA QUE SEJA CASO SUSPEITO DE NOVO CORONAVÍRUS (COVID-19)?':
    '¿EL PACIENTE TIENE EL PRÓXIMO CONTACTO CON UNA PERSONA QUE SE SOSPECHA DE UN CASO DE NUEVO CORONAVIRUS (COVID-19)?',
  NÃO: 'NO',
  'NÃO SABE': 'NO SABE',
  SIM: 'SÍ',
  'UNIDADE DE SAÚDE': 'UNIDAD DE SALUD',
  DOMICÍLIO: 'RESIDENCIA',
  'LOCAL DE TRABALHO': 'LUGAR DE TRABAJO',
  DESCONHECIDO: 'DESCONOCIDO',
  OUTRO: 'OTRO',
  Especificar: 'Para especificar',
  'O PACIENTE TEVE CONTATO PRÓXIMO COM UMA PESSOA QUE SEJA CASO CONFIRMADO DE NOVO CORONAVÍRUS (COVID-19)?':
    '¿EL PACIENTE TIENE EL PRÓXIMO CONTACTO CON UNA PERSONA CONFIRMADA COMO NUEVO CORONAVIRUS (COVID-19)?',
  'NOME DO CASO FONTE': 'FUENTE NOMBRE DEL CASO',
  'ESTEVE EM UNIDADE DE SAÚDE NOS ÚLTIMOS 14 DIAS?(PRONTO SOCORRO;INTERNAÇÃO; UTI)':
    '¿HA ESTADO EN UNIDAD DE SALUD EN LOS ÚLTIMOS 14 DÍAS? (ERROR; HOSPITALIZACIÓN; UCI)',
  'INFORMAR NOME DA UNIDADE': 'INFORMAR NOMBRE DE LA UNIDAD',
  'Selecione as doenças associadas': 'Seleccionar enfermedades asociadas',
  'HIPERTENSÃO ARTERIAL': 'HIPERTENCIÓN ARTERIAL',
  DIABETES: 'DIABETES',
  'ALTERAÇÃO COLESTEROL/TRIGLICÉRIDES': 'CAMBIO DE COLESTEROL / TRIGLICÉRIDOS',
  OBESIDADE: 'OBESIDAD',
  'DOENÇAS REUMATOLÓGICAS': 'ENFERMEDADES REUMATOLÓGICAS',
  Qual: 'Cual',
  'DPOC (ENFISEMA)': 'DPOC (ENFISEMA)',
  ASMA: 'ASMA',
  RINITE: 'RINITIS',
  'APNEIA DO SONO': 'APNEA DEL SUEÑO',
  'NEOPLASIA / CÂNCER': 'NEOPLASIA / CÁNCER',
  'INSUFICIÊNCIA RENAL': 'INSUFICIENCIA RENAL',
  'DOENÇAS HEPÁTICAS': 'ENFERMEDADES DEL HIGADO',
  OUTROS: 'OTROS',
  'Meus Laudos': 'Mis informes',
  Atendimento: 'Atención',
  Triagem: 'Cribado',
  Diagnóstico: 'Diagnóstico',
  Finalizado: 'Terminado',
  Positivo: 'Positive',
  Negativo: 'Negativo',
  'Mais opções': 'Mas opciones',
  'Meus Dados': 'Mis datos',
  Suporte: 'Soporte',
  'Fazer logout': 'Cerrar sesión',
  Telefone: 'Teléfono',
  'Entre em contato com nosso suporte por e-mail ou telefone': 'Póngase en contacto con nuestro soporte por correo electrónico o por teléfono',
  'D I A G N Ó S T I C O S': 'D I A G N O S T I C O S',
  'Cadastro conclúido! por favor, dirija-se ao laboratório escolhido para a realizar coleta': '¡Registro completado! por favor diríjase al laboratorio elegido para recogerlo',
  'Português': 'Portugués',
  'Inglês': 'Inglés',
  'Espanhol': 'Español',
  Mais: 'más',
  'Laboratório de Pesquisa por Cidade': 'Laboratorio de investigación por ciudad',
  'Selecione as ': 'Seleccione los ',
  'Selecione os ': 'Seleccione los ',
  'sinais ': 'signos ',
  'e ': 'y ',
  'sintomas ': 'síntomas ',
  'apresentados ': 'presentados',
  'doenças associadas': '',
  'Sobrenome': 'Apellido',
  'Buscar por Cidade': 'Buscar por ciudad',
  'Pedido': 'Pedido',
  'Tipo de exame': 'Tipo de examen',
  'Tipo de amostra': 'Tipo de ejemplo',
  'Resultado': 'Resultado',
  'O paciente tem histórico de ': 'El paciente tiene antecedentes de ',
  'viagem recente? ': 'viaje reciente? ',
  '(período de 14 dias)': '(Período de 14 días)',
  'O paciente teve ': 'El paciente tenía ',
  'contato ': 'contacto ',
  'com algum caso suspeito ou confirmado de COVID-19?': 'con un caso sospechoso o confirmado de COVID-19?',
  'O paciente esteve em alguma ': 'El paciente estaba en alguna ',
  'Unidade de Saúde ': 'Unidad de salud ',
  'nos últimos 14 dias? (Pronto Socorro, Internação, UTI)': 'en los últimos 14 días? (Urgencias, Hospitalización, UCI)',
  'Coriza': 'Moquear',
  'Qual País': 'Cul País',
  'Ver Todos': 'Ver todo',
  'apresentados': 'presentados',
  'Salvar dados para login': 'Guardar datos de inicio de sesión',
  'Menu Biogenetics': 'Menú Biogenética',
  'Aqui você poderá editar os seus dados pessoais, idioma e mais': 'Aquí puede editar sus datos personales, idioma y más',
  'DADOS DO USUÁRIO': 'DATOS DEL USUARIO',
  'TERMOS DE USO': 'TERMINOS DE USO',
  'IDIOMAS': 'IDIOMAS',
  'CONTATO': 'CONTACTO',
  'SAIR': 'DESCONECTAR',
  'Menu': 'Menú',
  'Perfil': 'Perfil',
  'Download realizado com sucesso': 'Descarga exitosa',
  'Consulte o status e o resultado dos seus exames realizados': 'Verifique el estado y los resultados de sus exámenes realizados',
  'Exame': 'Examen',
  'Exames': 'Examens',
  'EXAME': 'EXAMEN',
  'Laudo': 'Informe',
  'Paciente': 'Paciente',
  'DATA': 'FECHA',
  'VER LAUDO': 'VISTA DEL INFORME',
  'Baixar PDF': 'Descargar PDF',
  'Como podemos te ajudar hoje? Escolha uma das opções abaixo': '¿Cómo podemos ayudarlo hoy? Elija una de las opciones siguientes',
  'Aqui você consegue encontrar os laboratórios mais próximos de você': 'Aquí puede encontrar los laboratorios más cercanos a usted',
  'Buscar por CEP': 'Buscar por código postal',
  'INICIAR': 'COMIENZO',
  'Início': 'COMIENZO',
  'TELEFONE': 'TELÉFONO',
  'Aqui estão os laboratórios mais próximos de você': 'Aquí están los laboratorios más cercanos a ti',
  LIGAR: 'PARA CONECTAR',
  'Termos de Uso': 'Terminos de uso'
};
